FROM amazoncorretto:11-alpine
EXPOSE 8761
ADD target/eureka-servidor-ecommerce-0.0.1-SNAPSHOT.jar eureka-servidor-ecommerce-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/eureka-servidor-ecommerce-0.0.1-SNAPSHOT.jar"]